spring:
  application:
    name: flash-sale-demo
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flash_sale_local?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
  server:
    port: 9999

redisson:
  address : redis://127.0.0.1:6379
  password: 123456
  database: 0